config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects, except: [:show] do
    member do
      post :toggle_archive
    end

    resources :lists, except: [:show] do
      resources :todos, except: [:show] do
        member do
          post :toggle_complete
        end
      end
    end
  end

  resources :labels

  resource :session, only: %i[new create destroy]
  get 'password_reset/:id/:token/edit' => 'password_resets#edit', as: :edit_password_reset
  patch 'password_reset/:id/:token' => 'password_resets#update', as: :password_reset
  resources :password_reset_authorizations, only: %i[new create]
  resource :registration, except: %i[index]

end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :project
  has_many :todos, dependent: :destroy

  default_scope -> { includes(:todos).order("todos.due_date ASC") }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :load_project
  before_action :load_list, only: [:edit, :update, :destroy]

  def index
    @lists = @project.lists
  end

  def new
    @list = List.new
  end

  def create
    @list = @project.lists.new list_params
    if @list.save
      redirect_to project_lists_path(@project), notice: 'List created'
    else
      render :back, notice: 'Error! List could not be created'
    end
  end

  def edit
  end

  def update
    if @list.update! list_params
      redirect_to project_lists_path(@project), notice: 'List updated'
    else
      render :back, notice: 'Error! List could not be updated'
    end
  end

  def destroy
    if @list.destroy!
      redirect_to project_lists_path(@project), notice: 'List deleted'
    else
      render :back, notice: 'Error! List could not be deleted'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :project_id)
  end

  def load_project
    @project = Project.find params[:project_id]
  end

  def load_list
    @list = List.find params[:id]
  end
end

app/views/lists/_form.html.erb
<div class="card shadow-sm">
  <div class="card-body">
    <%= form_for [@project, @list] do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, required: true, class: 'form-control mb-2' %>
      <%= button_tag type: 'submit', class: "btn btn-outline-primary", data: { disable_with: "<i class='fas fa-spin fa-spinner'></i>"} do %>
        Save <i class="fas fa-check"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path, class: 'black' %></li>
    <li class="breadcrumb-item"><%= link_to @project.name, project_lists_path(@project), class: 'black' %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @list.name %></li>
  </ol>
</nav>

<%= render 'form' %>

app/views/lists/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path, class: 'black' %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @project.name %></li>
  </ol>
</nav>

<div class="card shadow-sm">
  <div class="card-body">
    <h4>Tasks overview</h4>
    <p>Due today: <%= @project.today_todos.count %></p>
    <p class="red">Overdue: <%= @project.overdue_todos.count %></p>
  </div>
</div>

<div class="mt-3 mb-2">
  <%= link_to new_project_list_path(@project), class: 'no-text-decor' do %>
    New list <i class="fas fa-plus-circle"></i>
  <% end %>
</div>

<div class="card-columns">
  <% @lists.each do |list| %>
    <div class="card shadow-sm">
      <div class="card-body">
        <h5 class="mb-2"><%= list.name %></h5>

        <ul class="pl-3 mb-0">
          <% list.todos.all_uncompleted.display_order.first(5).each do |todo| %>
            <li><%= todo.description.truncate(30) %></li>
          <% end -%>
        </ul>

        <% if list.todos.all_uncompleted.count <= 0 %><p class="text-muted m-0">nothing to do here...</p><% end -%>

        <div class="mt-2">
          <% if list.todos.all_uncompleted.count > 0 %>
            <span class="text-muted"><%= list.todos.all_uncompleted.count %> uncompleted <%= if list.todos.all_uncompleted.count == 1 then "todo" else "todos" end %></span>
          <% else %>
            <i class="fas fa-check green" style="font-size: 18px;"></i> All completed!
          <% end -%>
        </div>
      </div>
      <div class="card-footer">
        <%= link_to "View", project_list_todos_path(@project, list), class: 'no-text-decor p-0 pr-3' %>
        <%= link_to "Edit", edit_project_list_path(@project, list), class: 'no-text-decor p-0 pr-3' %>
        <%= link_to "Delete", project_list_path(@project, list), method: :delete, data: {confirm: 'Delete ' + list.name + '?'}, class: 'no-text-decor p-0 pr-3 red' %>
      </div>
    </div>
  <% end %>
</div>

<% if @lists.count == 0 %>
  <p class="text-muted">No lists</p>
<% end %>

app/views/lists/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path, class: 'black' %></li>
    <li class="breadcrumb-item"><%= link_to @project.name, project_lists_path(@project), class: 'black' %></li>
    <li class="breadcrumb-item active" aria-current="page">New List</li>
  </ol>
</nav>

<%= render 'form' %>