config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects, except: [:show] do
    member do
      post :toggle_archive
    end

    resources :lists, except: [:show] do
      resources :todos, except: [:show] do
        member do
          post :toggle_complete
        end
      end
    end
  end

  resources :labels

  resource :session, only: %i[new create destroy]
  get 'password_reset/:id/:token/edit' => 'password_resets#edit', as: :edit_password_reset
  patch 'password_reset/:id/:token' => 'password_resets#update', as: :password_reset
  resources :password_reset_authorizations, only: %i[new create]
  resource :registration, except: %i[index]

end

app/models/label.rb
class Label < ApplicationRecord
  belongs_to :user
  has_many :projects
  before_destroy :remove_label_from_projects

  default_scope -> { order(name: :asc) }

  private def remove_label_from_projects
    projects.update_all label_id: nil
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :load_label, only: [:edit, :update, :destroy]

  def index
    @labels = Current.user.labels
  end

  def new
    @label = Label.new
  end

  def create
    label = Current.user.labels.new label_params
    if label.save
      redirect_to labels_path, notice: 'Label created'
    else
      render :back, notice: 'Error! Label could not be created'
    end
  end

  def edit
  end

  def update
    if @label.update! label_params
      redirect_to labels_path, notice: 'Label updated'
    else
      render :back, notice: 'Error! Label could not be updated'
    end
  end

  def destroy
    if @label.destroy!
      redirect_to labels_path, notice: 'Label deleted'
    else
      render :back, notice: 'Error! Project could not be deleted'
    end
  end

  private

  def label_params
    params.require(:label).permit(:name)
  end

  def load_label
    @label = Label.find params[:id]
  end
end

app/views/labels/_form.html.erb
<div class="card shadow-sm">
  <div class="card-body">
    <%= form_for @label do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, required: true, class: 'form-control mb-2' %>
      <%= button_tag type: 'submit', class: "btn btn-outline-primary", data: { disable_with: "<i class='fas fa-spin fa-spinner'></i>"} do %>
        Save <i class="fas fa-check"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/labels/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path , class: 'black' %></li>
    <li class="breadcrumb-item"><%= link_to "Labels", labels_path , class: 'black' %></li>
    <li class="breadcrumb-item active" aria-current="page">Edit</li>
  </ol>
</nav>

<%= render 'form' %>

app/views/labels/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path, class: 'black' %></li>
    <li class="breadcrumb-item active" aria-current="page">Labels</li>
  </ol>
</nav>

<div class="mt-3 mb-2">
  <%= link_to new_label_path, class: 'no-text-decor' do %>
    New label <i class="fas fa-plus-circle"></i>
  <% end %>
</div>

<div class="row">
  <% @labels.each do |label| %>
    <div class="col-sm-6 col-lg-4">
      <div class="card shadow-sm mb-2">
        <div class="card-body">

          <div class='pt-2 pb-2' style='display: flex; justify-content: space-between;'>
            <p><i class="fas fa-tag mr-2"></i> <%= label.name %></p>
            <div>
              <%= link_to edit_label_path(label), class: 'no-text-decor', data: {toggle: 'tooltip'}, title: 'Edit label' do %>
                <i class="far fa-edit black"></i>
              <% end -%>
              <%= link_to label_path(label), class: 'no-text-decor', method: :delete, data: { confirm: "Delete label?", toggle: 'tooltip' }, title: 'Delete todo' do %>
                <i class="far fa-trash-alt black"></i>
              <% end -%>
            </div>
          </div>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/labels/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path , class: 'black' %></li>
    <li class="breadcrumb-item"><%= link_to "Labels", labels_path , class: 'black' %></li>
    <li class="breadcrumb-item active" aria-current="page">New</li>
  </ol>
</nav>

<%= render 'form' %>