config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects, except: [:show] do
    member do
      post :toggle_archive
    end

    resources :lists, except: [:show] do
      resources :todos, except: [:show] do
        member do
          post :toggle_complete
        end
      end
    end
  end

  resources :labels

  resource :session, only: %i[new create destroy]
  get 'password_reset/:id/:token/edit' => 'password_resets#edit', as: :edit_password_reset
  patch 'password_reset/:id/:token' => 'password_resets#update', as: :password_reset
  resources :password_reset_authorizations, only: %i[new create]
  resource :registration, except: %i[index]

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :label, optional: true
  has_many :lists, dependent: :destroy
  has_many :todos, through: :lists

  default_scope -> { includes(:todos).order("todos.due_date ASC") }
  scope :active, -> { where(archived_at: nil) }
  scope :archived, -> { where.not(archived_at: nil) }

  def archived?
    archived_at != nil
  end

  def toggle_archive
    if archived?
      update! archived_at: nil
    else
      update! archived_at: DateTime.now.in_time_zone
    end
  end

  def today_todos
    todos.where(completed_at: nil).where('due_date = ?', Time.zone.today)
  end

  def overdue_todos
    todos.where(completed_at: nil).where('due_date < ?', Time.zone.today)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_project, only: [:toggle_archive, :edit, :update, :destroy]

  def index
    @filter_projects = FilterProjects.execute(filter_params)
    @projects = @filter_projects.projects
    @overdue_todos = Todo.overdue
    @today_todos = Todo.due_today
  end

  def new
    @project = Project.new
  end

  def create
    @project = Current.user.projects.new project_params
    if @project.save
      redirect_to project_lists_path(@project), notice: 'Project created'
    else
      render :back, notice: 'Error! Project could not be created'
    end
  end

  def edit
  end

  def update
    if @project.update! project_params
      redirect_to projects_path, notice: 'Project updated'
    else
      render :back, notice: 'Error! Project could not be updated'
    end
  end

  def toggle_archive
    if @project.toggle_archive
      redirect_to projects_path, notice: 'Project archived'
    else
      render :back, notice: 'Error!'
    end
  end

  def destroy
    if @project.destroy!
      redirect_to projects_path, notice: 'Project deleted'
    else
      render :back, notice: 'Error! Project could not be deleted'
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :label_id)
  end

  def filter_params
    if params[:filter_projects]
      params.require(:filter_projects).permit(:query, :status, :label_id).merge(user: Current.user)
    else
      {user: Current.user}
    end
  end

  def load_project
    @project = Project.find params[:id]
  end
end

app/views/projects/_form.html.erb
<div class="card shadow-sm">
  <div class="card-body">
    <%= form_for @project do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, required: true, class: 'form-control mb-2' %>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control mb-2', rows: 5 %>
      <%= f.label :label %><br>
      <div style='display: inline-block;'>
        <%= f.select :label_id,
          [["None", ""]] + Current.user.labels.map { |l| [l.name, l.id] },
          {},
          {class: 'form-control mb-2'}
        %>
      </div><br>
      
      <%= button_tag type: 'submit', class: "btn btn-outline-primary", data: { disable_with: "<i class='fas fa-spin fa-spinner'></i>"} do %>
        Save <i class="fas fa-check"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path , class: 'black' %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @project.name %></li>
  </ol>
</nav>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="account-header">
  <p class="text-muted">Logged in as <%= Current.user.email %></p>
  <div>
    <p><%= link_to "My account", edit_registration_path, class: 'mr-3 no-text-decor' %><%= link_to "Log out", session_path, method: :delete, class: 'no-text-decor' %></p>
  </div>
</div>


<div class="card shadow-sm">
  <div class="card-body">
    <h5>Filter projects</h5>
    <%= form_for @filter_projects, url: projects_path, method: :get do |f| %>
      <div class="mt-2">
        <div class="mb-1">
          <%= f.label :search %>
          <%= f.text_field :query, class: 'form-control' %>
        </div>
        
        <div class="project-filters">
          <div class="mr-3">
            <%= f.label :status %>
            <%= f.select :status,
              [["Active", ""], ["Archived", 'archived'], ['All', 'all']],
              {},
              {class: 'form-control'}
            %>
          </div>
          <div>
            <%= f.label :label %>
            <%= f.select :label_id,
              [["All", ""], ["None", "none"]] + Current.user.labels.map { |l| [l.name, l.id] },
              {},
              {class: 'form-control'}
            %>
          </div>
        </div>
        
      </div>
      <div class="mt-2">
        <%= button_tag type: 'submit', class: "btn btn-outline-primary" do %>
          Filter <i class="fas fa-check"></i>
        <% end %>
        <% if params[:filter_projects] %>
          <%= link_to projects_path, class: 'btn btn-link red no-text-decor' do %>
            Clear <i class="fas fa-times"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="mt-3 mb-2">
  <%= link_to new_project_path, class: 'no-text-decor' do %>
    New project <i class="fas fa-plus-circle"></i>
  <% end %>

  <%= link_to labels_path, class: 'no-text-decor ml-3' do %>
    Manage labels <i class="fas fa-tasks"></i>
  <% end %>
</div>

<div class="card-columns">
  <% @projects.each do |project| %>
    <div class="card shadow-sm">
      <div class="card-body">
        <h5 class="mb-2"><%= project.name %></h5>

        <p class="m-0"><%= project.description %></p>

        <div class="mt-2 text-muted">
          <% if project.todos.all_uncompleted.count > 0 %>
            <%= project.todos.all_uncompleted.count %> uncompleted <%= if project.todos.all_uncompleted.count == 1 then "todo" else "todos" end %>
          <% else %>
            <i class="fas fa-check green" style="font-size: 18px;"></i> All completed!
          <% end -%>
        </div>
      </div>
      <div class="card-footer">
        <%= link_to "View", project_lists_path(project), class: 'no-text-decor p-0 pr-3' %>
        <%= link_to "Edit", edit_project_path(project), class: 'no-text-decor p-0 pr-3' %>
        <%= link_to "#{project.archived? ? 'Unarchive' : 'Archive'}", toggle_archive_project_path(project), method: :post, data: {confirm: 'Are you sure?'}, class: 'no-text-decor p-0 pr-3' %>
        <%= link_to "Delete", project_path(project), method: :delete, data: {confirm: 'Are you sure?'}, class: 'no-text-decor p-0 pr-3 red' %>
      </div>
    </div>
  <% end %>
</div>

<% if params[:filter_projects] && @projects.count == 0 %>
  <p class="text-muted">No results</p>
<% elsif !params[:filter_projects] && @projects.count == 0 %>
  <p class="text-muted">No projects</p>
<% end %>

app/views/projects/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path , class: 'black' %></li>
    <li class="breadcrumb-item active" aria-current="page">New</li>
  </ol>
</nav>

<%= render 'form' %>