config/routes.rb
Rails.application.routes.draw do

  root 'projects#index'

  resources :projects, except: [:show] do
    member do
      post :toggle_archive
    end

    resources :lists, except: [:show] do
      resources :todos, except: [:show] do
        member do
          post :toggle_complete
        end
      end
    end
  end

  resources :labels

  resource :session, only: %i[new create destroy]
  get 'password_reset/:id/:token/edit' => 'password_resets#edit', as: :edit_password_reset
  patch 'password_reset/:id/:token' => 'password_resets#update', as: :password_reset
  resources :password_reset_authorizations, only: %i[new create]
  resource :registration, except: %i[index]

end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :list

  scope :display_order, -> { order(completed_at: :desc, due_date: :asc, description: :asc) }
  scope :due_today, -> { where(completed_at: nil).where('due_date = ?', Time.zone.today) }
  scope :overdue, -> { where(completed_at: nil).where('due_date < ?', Time.zone.today) }
  scope :in_progress, -> { where(completed_at: nil) }
  scope :completed, -> { where.not(completed_at: nil) }

  def completed?
    completed_at != nil
  end

  def toggle_complete
    if completed?
      update! completed_at: nil
    else
      update! completed_at: DateTime.now.in_time_zone
    end
  end

  def self.all_completed
    Todo.where.not(completed_at: nil)
  end

  def self.all_uncompleted
    Todo.where(completed_at: nil)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :load_project
  before_action :load_list
  before_action :load_todo, only: [:edit, :update, :show, :destroy, :toggle_complete]

  def index
    @search = TodoSearch.execute search_params
    @todos = @search.todos
    @tab = params[:tab]
  end

  def create
    @todo = @list.todos.new todo_params
    if @todo.save
      redirect_to project_list_todos_path(@project, @list), notice: 'Todo created'
    else
      render :back, notice: 'Error! Todo could not be created'
    end
  end

  def update
    tab = @todo.completed? ? 'completed' : nil
    if @todo.update! todo_params
      redirect_to project_list_todos_path(@project, @list, tab: tab), notice: 'Todo updated'
    else
      render :back, notice: 'Error! Todo could not be updated'
    end
  end

  def destroy
    tab = @todo.completed? ? 'completed' : nil
    if @todo.destroy!
      redirect_to project_list_todos_path(@project, @list, tab: tab), notice: 'Todo deleted'
    else
      render :back, notice: 'Error! Todo could not be deleted'
    end
  end

  def toggle_complete
    tab = @todo.completed? ? 'completed' : nil
    if @todo.toggle_complete
      redirect_to project_list_todos_path(@project, @list, tab: tab)
    else
      render :back, notice: 'Error!'
    end
  end

  private

  def search_params
    if params[:todo_search]
      params.require(:todo_search).permit(:query).merge(list_id: @list.id)
    else
      {list_id: @list.id}
    end
  end

  def load_todo
    @todo = Todo.find params[:id]
  end

  def load_project
    @project = Project.find params[:project_id]
  end

  def load_list
    @list = List.find params[:list_id]
  end

  def todo_params
    params.require(:todo).permit(:description, :completed_at, :due_date, :list_id)
  end
end

app/views/todos/_completed.html.erb
<% if @todos.completed.count > 0 %>

  <table class="table table-borderless table-hover d-none d-md-table" style="table-layout:fixed;">
    <tr>
      <th style="width: 52px;"></th>
      <th colspan="3">Description</th>
      <th class="text-center">Due Date</th>
      <th class="text-center">Actions</th>
    </tr>

    <% @todos.completed.display_order.each do |todo| %>
      <tr>
        <td style="width: 52px; padding-top: 10px;">
          <%= link_to toggle_complete_project_list_todo_path(@project, @list, todo), class: 'no-text-decor', method: :post do %>
            <i class="far fa-check-square fa-2x black"></i>
          <% end %>
        </td>
        <td colspan="3"><%= todo.description %></td>
        <td class="text-center"><span style="text-decoration: line-through;"><%= todo.due_date.strftime("%b %e") %></span></td>
        <td style="font-size: 20px;" class="text-center">
          <%= link_to edit_project_list_todo_path(@project, @list, todo), class: 'no-text-decor', data: {toggle: 'tooltip'}, title: 'Edit todo' do %>
            <i class="far fa-edit black"></i>
          <% end -%>

          <%= link_to project_list_todo_path(@project, @list, todo), class: 'no-text-decor', method: :delete, data: { confirm: "Delete todo?", toggle: 'tooltip' }, title: 'Delete todo' do %>
            <i class="far fa-trash-alt black"></i>
          <% end -%>
        </td>
      </tr>
    <% end %>
  </table>

  <div class="d-md-none mt-3">
    <% @todos.completed.display_order.each do |todo| %>
      <p><%= todo.description %></p>
      <p style="text-decoration: line-through;">Due <%= todo.due_date.strftime("%b %e") %></p>
      <p>
        <%= link_to toggle_complete_project_list_todo_path(@project, @list, todo), class: 'no-text-decor black mr-2', method: :post do %>
          <i class="far fa-check-square"></i> Mark uncomplete
        <% end %>
          
        <%= link_to edit_project_list_todo_path(@project, @list, todo), class: 'no-text-decor black mr-2' do %>
          <i class="far fa-edit"></i> Edit
        <% end -%>

        <%= link_to project_list_todo_path(@project, @list, todo), class: 'no-text-decor black', method: :delete, data: { confirm: "Delete todo?" } do %>
          <i class="far fa-trash-alt"></i> Delete
        <% end -%>
      </p>
      
      <% if todo != @todos.last %>
        <hr class="mt-2 mb-2">
      <% end %>
    <% end %>
  </div>
<% else %>
  <p class="text-muted mt-2 mb-0">No completed todos</p>
<% end %>

app/views/todos/_in_progress.html.erb
<% if @todos.in_progress.count > 0 %>
  <table class="table table-borderless table-hover d-none d-md-table" style="table-layout:fixed;">
    <tr>
      <th style="width: 52px;"></th>
      <th colspan="3">Description</th>
    
      <th class="text-center">Due Date</th>
      <th class="text-center">Actions</th>
    </tr>

    <% @todos.in_progress.display_order.each do |todo| %>
      <tr>
        <td style="width: 52px; padding-top: 10px;">
          <%= link_to toggle_complete_project_list_todo_path(@project, @list, todo), class: 'no-text-decor', method: :post do %>
            <i class="far fa-square black fa-2x"></i>
          <% end %>
        </td>
        <td colspan="3"><%= todo.description %></td>
        <td class="text-center">
          <% if todo.due_date < Time.zone.today %>
            <span style="color: red;"><%= todo.due_date.strftime("%b %e") %></span>
          <% else %>
            <%= todo.due_date.strftime("%b %e") %>
          <% end %>
        </td>
        <td style="font-size: 20px;" class="text-center">
          <%= link_to edit_project_list_todo_path(@project, @list, todo), class: 'no-text-decor', data: {toggle: 'tooltip'}, title: 'Edit todo' do %>
            <i class="far fa-edit black"></i>
          <% end -%>

          <%= link_to project_list_todo_path(@project, @list, todo), class: 'no-text-decor', method: :delete, data: { confirm: "Delete todo?", toggle: 'tooltip' }, title: 'Delete todo' do %>
            <i class="far fa-trash-alt black"></i>
          <% end -%>
        </td>
      </tr>
    <% end %>
  </table>

  <div class="d-md-none mt-3">
    <% @todos.in_progress.display_order.each do |todo| %>
      <p><%= todo.description %></p>
      <p>
        <% if todo.due_date < Time.zone.today %>
          <span style="color: red;">Due <%= todo.due_date.strftime("%b %e") %></span>
        <% else %>
          Due <%= todo.due_date.strftime("%b %e") %>
        <% end %>
      </p>
      <p>
        <%= link_to toggle_complete_project_list_todo_path(@project, @list, todo), class: 'no-text-decor black mr-2', method: :post do %>
          <i class="far fa-square"></i> Mark complete
        <% end %>
        
        <%= link_to edit_project_list_todo_path(@project, @list, todo), class: 'no-text-decor black mr-2' do %>
          <i class="far fa-edit"></i> Edit
        <% end -%>

        <%= link_to project_list_todo_path(@project, @list, todo), class: 'no-text-decor black', method: :delete, data: { confirm: "Delete todo?" } do %>
          <i class="far fa-trash-alt"></i> Delete
        <% end -%>
      </p>
      
      <% if todo != @todos.last %>
        <hr class="mt-2 mb-2">
      <% end %>
    <% end %>
  </div>
<% else %>
  <p class="text-muted mt-2 mb-0">No uncompleted todos</p>
<% end %>

app/views/todos/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path, class: 'black' %></li>
    <li class="breadcrumb-item"><%= link_to @project.name, project_lists_path(@project), class: 'black' %></li>
    <li class="breadcrumb-item"><%= link_to @list.name, project_list_todos_path(@project, @list), class: 'black' %></li>
    <li class="breadcrumb-item active" aria-current="page">Edit Todo</li>
  </ol>
</nav>

<div class="card shadow">
  <div class="card-body">
    <h5 class="mb-3">Edit Todo</h5>
    
    <%= form_for [@project, @list, @todo] do |f| %>
      <%= f.text_field :description, class: 'form-control mb-1', rows: 5 %>
      <%= f.date_field :due_date, class: 'form-control mb-2' %>
      <%= button_tag type: 'submit', class: "btn btn-outline-primary", data: { disable_with: "<i class='fas fa-spin fa-spinner'></i>"} do %>
        Save <i class="fas fa-check"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/todos/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Projects", projects_path, class: 'black' %></li>
    <li class="breadcrumb-item"><%= link_to @project.name, project_lists_path(@project), class: 'black' %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @list.name %></li>
  </ol>
</nav>

<div class="card shadow-sm mb-3">
  <div class="card-body">
    <h5 class="mb-2">New todo</h5>

    <%= form_for [@project, @list, Todo.new] do |f| %>
      <%= f.label :description %>
      <div class="input-group mb-1">
        <%= f.text_field :description, placeholder: 'enter todo...', class: 'form-control', required: true, autofocus: true %>
      </div>
      <%= f.label :due_date %>
      <div class="input-group">
        <%= f.date_field :due_date, value: Date.today + 7.days, class: 'form-control' %>
      </div>
      <button class="btn btn-outline-primary mt-2" data-disable-with="<i class='fas fa-spin fa-spinner'></i>">Add <i class="fas fa-check"></i></button>
    <% end %>
  </div>
</div>

<div class="card shadow-sm">
  <div class="card-body">
    <h5 class="mb-3">Todos</h5>
      <%= form_for @search, url: project_list_todos_path(@project, @list), method: :get, html: {class: "form"} do |f| %>
        <%= hidden_field_tag :tab, @tab %>
        <div class="input-group mb-0">
          <%= f.text_field :query, placeholder: "Search todos...", class: "form-control border-right-0", required: true %>
          <span class="input-group-append">
            <button class="btn btn-outline-secondary search-btn border border-left-0" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </span>
        </div>
        <% if params[:todo_search] %>
          <div class="mt-1">
            <%= link_to project_list_todos_path(@project, @list, tab: @tab), class: 'red' do %>
              <i class="fas fa-times-circle red"></i> Clear search
            <% end %>
          </div>
        <% end %>
      <% end %>

      <div class="btn-group mt-2 mb-1" role="group">
        <%= link_to 'In progress', project_list_todos_path(@project, @list), style: '', class: "btn btn-sm #{if @tab != 'completed' then 'btn-primary' else 'btn-outline-primary' end}" %>
        <%= link_to 'Completed', project_list_todos_path(@project, @list, tab: 'completed'), style: 'margin-left: .35px;', class: "btn btn-sm #{if @tab != 'completed' then 'btn-outline-primary' else 'btn-primary' end}" %>
      </div>

      <% if @tab == 'completed' %>
        <%= render 'completed' %>
      <% else %>
        <%= render 'in_progress' %>
      <% end %>
  </div>
</div>

<script>
    $(document).ready(function(){
      $('[data-toggle="tooltip"]').tooltip();
    });
</script>